version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-ugc-research
    ports:
      - "8123:8123"
      - "9000:9000"

  vertica:
    image: vertica/vertica-ce
    container_name: vertica-ugc-research
    ports:
      - "5433:5433"
      - "5444:5444"
